apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: vault-team
  namespace: vault-ns
spec:
  interval: 1m
  url: https://github.com/EvanAmstutz/vault-poc
  ref:
    branch: main
  secretRef: 
    name: vault-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-team
  namespace: vault-ns
spec:
  serviceAccountName: vault-team
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: vault-team
  prune: true
  validation: client


